"""add policy section embeddings

Revision ID: 20260903_0004
Revises: 20260903_0003
Create Date: 2026-09-03 23:30:31.422916
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import VECTOR

revision: str = "20260903_0004"
down_revision: str | None = "20260903_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "policy_sections",
        sa.Column("embedding", VECTOR(dim=768), nullable=True),
        schema="knowledge",
    )
    op.add_column(
        "policy_sections",
        sa.Column("embedding_model", sa.String(length=96), nullable=True),
        schema="knowledge",
    )
    op.add_column(
        "policy_sections",
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
        schema="knowledge",
    )
    op.create_index(
        "ix_policy_sections_embedding_hnsw",
        "policy_sections",
        ["embedding"],
        unique=False,
        schema="knowledge",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_policy_sections_embedding_hnsw",
        table_name="policy_sections",
        schema="knowledge",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_column("policy_sections", "embedded_at", schema="knowledge")
    op.drop_column("policy_sections", "embedding_model", schema="knowledge")
    op.drop_column("policy_sections", "embedding", schema="knowledge")
    # ### end Alembic commands ###
