"""add case management and ai runtime

Revision ID: 20260903_0003
Revises: 20260903_0002
Create Date: 2026-09-03 23:16:37.414727
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260903_0003"
down_revision: str | None = "20260903_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA case_management")
    op.execute("CREATE SCHEMA ai_runtime")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations_accounts",
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations_accounts")),
        sa.UniqueConstraint("username", name=op.f("uq_operations_accounts_username")),
        schema="case_management",
    )
    op.create_table(
        "cases",
        sa.Column("public_reference", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("external_request_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("claimed_customer_reference", sa.String(length=32), nullable=True),
        sa.Column("complaint_text", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('normal', 'high', 'urgent')", name=op.f("ck_cases_valid_priority")
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'simulator', 'api')", name=op.f("ck_cases_valid_source")
        ),
        sa.CheckConstraint(
            "status IN ('received', 'queued', 'processing', 'pending_approval', "
            "'resolved', 'human_investigation', 'failed')",
            name=op.f("ck_cases_valid_status"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(complaint_text)) > 0", name=op.f("ck_cases_nonempty_complaint")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_cases_positive_version")),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["business.customers.id"], name=op.f("fk_cases_customer_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("public_reference", name=op.f("uq_cases_public_reference")),
        sa.UniqueConstraint("source", "external_request_key", name=op.f("uq_cases_source")),
        schema="case_management",
    )
    op.create_index(
        "ix_cases_customer_received",
        "cases",
        ["customer_id", "received_at"],
        unique=False,
        schema="case_management",
    )
    op.create_index(
        "ix_cases_status_received",
        "cases",
        ["status", "received_at"],
        unique=False,
        schema="case_management",
    )
    op.create_table(
        "operations_sessions",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["case_management.operations_accounts.id"],
            name=op.f("fk_operations_sessions_account_id_operations_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations_sessions")),
        schema="case_management",
    )
    op.create_index(
        "ix_operations_sessions_expiry",
        "operations_sessions",
        ["expires_at"],
        unique=False,
        schema="case_management",
    )
    op.create_index(
        "ix_operations_sessions_token",
        "operations_sessions",
        ["token_hash"],
        unique=True,
        schema="case_management",
    )
    op.create_table(
        "case_runs",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("architecture_version", sa.String(length=64), nullable=False),
        sa.Column("model_provider", sa.String(length=48), nullable=True),
        sa.Column("model_name", sa.String(length=96), nullable=True),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed', 'interrupted')",
            name=op.f("ck_case_runs_valid_status"),
        ),
        sa.CheckConstraint("run_number > 0", name=op.f("ck_case_runs_positive_run_number")),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_management.cases.id"],
            name=op.f("fk_case_runs_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_runs")),
        sa.UniqueConstraint("case_id", "run_number", name=op.f("uq_case_runs_case_id")),
        schema="ai_runtime",
    )
    op.create_index(
        "ix_case_runs_case_created",
        "case_runs",
        ["case_id", "created_at"],
        unique=False,
        schema="ai_runtime",
    )
    op.create_table(
        "case_events",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=24), nullable=False),
        sa.Column("actor_reference", sa.String(length=128), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('customer', 'employee', 'system', 'agent')",
            name=op.f("ck_case_events_valid_actor_type"),
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_case_events_positive_sequence")),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_management.cases.id"],
            name=op.f("fk_case_events_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_events")),
        sa.UniqueConstraint("case_id", "sequence", name=op.f("uq_case_events_case_id")),
        schema="case_management",
    )
    op.create_index(
        "ix_case_events_case_occurred",
        "case_events",
        ["case_id", "occurred_at", "sequence"],
        unique=False,
        schema="case_management",
    )
    op.create_table(
        "processing_jobs",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'leased' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL) "
            "OR (status <> 'leased')",
            name=op.f("ck_processing_jobs_leased_fields_present"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'leased', 'retry_wait', 'succeeded', 'dead_letter', 'cancelled')",
            name=op.f("ck_processing_jobs_valid_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_processing_jobs_nonnegative_attempt_count")
        ),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_processing_jobs_positive_max_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_management.cases.id"],
            name=op.f("fk_processing_jobs_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
        sa.UniqueConstraint("case_id", "job_type", name=op.f("uq_processing_jobs_case_id")),
        schema="case_management",
    )
    op.create_index(
        "ix_processing_jobs_claim",
        "processing_jobs",
        ["status", "available_at", "created_at"],
        unique=False,
        schema="case_management",
    )
    op.create_index(
        "ix_processing_jobs_lease_expiry",
        "processing_jobs",
        ["lease_expires_at"],
        unique=False,
        schema="case_management",
    )
    op.create_table(
        "evidence_items",
        sa.Column("case_run_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("condition", sa.String(length=24), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_reference", sa.String(length=128), nullable=True),
        sa.Column("tool_call_reference", sa.String(length=128), nullable=True),
        sa.Column("observed_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition IN ('present', 'known_absent', 'missing', 'unknown', "
            "'contradictory', 'unavailable', 'not_applicable')",
            name=op.f("ck_evidence_items_valid_condition"),
        ),
        sa.ForeignKeyConstraint(
            ["case_run_id"],
            ["ai_runtime.case_runs.id"],
            name=op.f("fk_evidence_items_case_run_id_case_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
        schema="ai_runtime",
    )
    op.create_index(
        "ix_evidence_items_run_type",
        "evidence_items",
        ["case_run_id", "evidence_type"],
        unique=False,
        schema="ai_runtime",
    )
    op.create_table(
        "investigation_plans",
        sa.Column("case_run_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_investigation_plans_positive_revision")),
        sa.ForeignKeyConstraint(
            ["case_run_id"],
            ["ai_runtime.case_runs.id"],
            name=op.f("fk_investigation_plans_case_run_id_case_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigation_plans")),
        sa.UniqueConstraint(
            "case_run_id", "revision", name=op.f("uq_investigation_plans_case_run_id")
        ),
        schema="ai_runtime",
    )
    op.create_table(
        "policy_retrievals",
        sa.Column("case_run_id", sa.Uuid(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("effective_on", sa.Date(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retrieval_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ranked_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selected_section_ids", postgresql.ARRAY(sa.String(length=160)), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_run_id"],
            ["ai_runtime.case_runs.id"],
            name=op.f("fk_policy_retrievals_case_run_id_case_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_retrievals")),
        schema="ai_runtime",
    )
    op.create_index(
        "ix_policy_retrievals_run",
        "policy_retrievals",
        ["case_run_id"],
        unique=False,
        schema="ai_runtime",
    )
    op.create_table(
        "resolution_proposals",
        sa.Column("case_run_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=64), nullable=False),
        sa.Column("disposition", sa.String(length=32), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("action_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_references", postgresql.ARRAY(sa.String(length=160)), nullable=False),
        sa.Column("policy_references", postgresql.ARRAY(sa.String(length=160)), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "disposition IN ('auto_resolve', 'human_approval', 'human_investigation')",
            name=op.f("ck_resolution_proposals_valid_disposition"),
        ),
        sa.ForeignKeyConstraint(
            ["case_run_id"],
            ["ai_runtime.case_runs.id"],
            name=op.f("fk_resolution_proposals_case_run_id_case_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_proposals")),
        sa.UniqueConstraint("case_run_id", name=op.f("uq_resolution_proposals_case_run_id")),
        schema="ai_runtime",
    )
    op.create_table(
        "verification_results",
        sa.Column("case_run_id", sa.Uuid(), nullable=False),
        sa.Column("supported", sa.Boolean(), nullable=False),
        sa.Column("missing_evidence", postgresql.ARRAY(sa.String(length=160)), nullable=False),
        sa.Column("contradictions", postgresql.ARRAY(sa.String(length=160)), nullable=False),
        sa.Column("unsupported_claims", postgresql.ARRAY(sa.String(length=160)), nullable=False),
        sa.Column("recommended_outcome", sa.String(length=64), nullable=False),
        sa.Column("recommended_disposition", sa.String(length=32), nullable=False),
        sa.Column("requires_human", sa.Boolean(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_run_id"],
            ["ai_runtime.case_runs.id"],
            name=op.f("fk_verification_results_case_run_id_case_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_results")),
        sa.UniqueConstraint("case_run_id", name=op.f("uq_verification_results_case_run_id")),
        schema="ai_runtime",
    )
    op.create_table(
        "action_intents",
        sa.Column("public_reference", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("case_run_id", sa.Uuid(), nullable=True),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_reference", sa.String(length=64), nullable=False),
        sa.Column("action_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'pending_approval', 'approved', 'rejected', "
            "'executing', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_action_intents_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_management.cases.id"],
            name=op.f("fk_action_intents_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["case_run_id"],
            ["ai_runtime.case_runs.id"],
            name=op.f("fk_action_intents_case_run_id_case_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_intents")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_action_intents_idempotency_key")),
        sa.UniqueConstraint("public_reference", name=op.f("uq_action_intents_public_reference")),
        schema="case_management",
    )
    op.create_index(
        "ix_action_intents_case_status",
        "action_intents",
        ["case_id", "status"],
        unique=False,
        schema="case_management",
    )
    op.create_table(
        "escalations",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("case_run_id", sa.Uuid(), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("resolved_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'resolved')",
            name=op.f("ck_escalations_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_management.cases.id"],
            name=op.f("fk_escalations_case_id_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["case_run_id"],
            ["ai_runtime.case_runs.id"],
            name=op.f("fk_escalations_case_run_id_case_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_account_id"],
            ["case_management.operations_accounts.id"],
            name=op.f("fk_escalations_resolved_by_account_id_operations_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escalations")),
        schema="case_management",
    )
    op.create_index(
        "ix_escalations_status_created",
        "escalations",
        ["status", "created_at"],
        unique=False,
        schema="case_management",
    )
    op.create_table(
        "approvals",
        sa.Column("action_intent_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')", name=op.f("ck_approvals_valid_decision")
        ),
        sa.ForeignKeyConstraint(
            ["action_intent_id"],
            ["case_management.action_intents.id"],
            name=op.f("fk_approvals_action_intent_id_action_intents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_account_id"],
            ["case_management.operations_accounts.id"],
            name=op.f("fk_approvals_decided_by_account_id_operations_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("action_intent_id", name=op.f("uq_approvals_action_intent_id")),
        schema="case_management",
    )
    op.create_table(
        "execution_attempts",
        sa.Column("action_intent_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("executor", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("external_reference", sa.String(length=128), nullable=True),
        sa.Column(
            "response_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('started', 'succeeded', 'failed', 'indeterminate')",
            name=op.f("ck_execution_attempts_valid_status"),
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_execution_attempts_positive_attempt_number")
        ),
        sa.ForeignKeyConstraint(
            ["action_intent_id"],
            ["case_management.action_intents.id"],
            name=op.f("fk_execution_attempts_action_intent_id_action_intents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_attempts")),
        sa.UniqueConstraint(
            "action_intent_id",
            "attempt_number",
            name=op.f("uq_execution_attempts_action_intent_id"),
        ),
        schema="case_management",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("execution_attempts", schema="case_management")
    op.drop_table("approvals", schema="case_management")
    op.drop_index(
        "ix_escalations_status_created", table_name="escalations", schema="case_management"
    )
    op.drop_table("escalations", schema="case_management")
    op.drop_index(
        "ix_action_intents_case_status", table_name="action_intents", schema="case_management"
    )
    op.drop_table("action_intents", schema="case_management")
    op.drop_table("verification_results", schema="ai_runtime")
    op.drop_table("resolution_proposals", schema="ai_runtime")
    op.drop_index("ix_policy_retrievals_run", table_name="policy_retrievals", schema="ai_runtime")
    op.drop_table("policy_retrievals", schema="ai_runtime")
    op.drop_table("investigation_plans", schema="ai_runtime")
    op.drop_index("ix_evidence_items_run_type", table_name="evidence_items", schema="ai_runtime")
    op.drop_table("evidence_items", schema="ai_runtime")
    op.drop_index(
        "ix_processing_jobs_lease_expiry", table_name="processing_jobs", schema="case_management"
    )
    op.drop_index(
        "ix_processing_jobs_claim", table_name="processing_jobs", schema="case_management"
    )
    op.drop_table("processing_jobs", schema="case_management")
    op.drop_index(
        "ix_case_events_case_occurred", table_name="case_events", schema="case_management"
    )
    op.drop_table("case_events", schema="case_management")
    op.drop_index("ix_case_runs_case_created", table_name="case_runs", schema="ai_runtime")
    op.drop_table("case_runs", schema="ai_runtime")
    op.drop_index(
        "ix_operations_sessions_token", table_name="operations_sessions", schema="case_management"
    )
    op.drop_index(
        "ix_operations_sessions_expiry", table_name="operations_sessions", schema="case_management"
    )
    op.drop_table("operations_sessions", schema="case_management")
    op.drop_index("ix_cases_status_received", table_name="cases", schema="case_management")
    op.drop_index("ix_cases_customer_received", table_name="cases", schema="case_management")
    op.drop_table("cases", schema="case_management")
    op.drop_table("operations_accounts", schema="case_management")
    op.execute("DROP SCHEMA ai_runtime")
    op.execute("DROP SCHEMA case_management")
    # ### end Alembic commands ###
